server:
  port: 8087

spring:
  application:
    name: "authuser"

  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    doc-expansion: none

logging:
  level:
    br.com.ead: trace  # Define o nível de logging para o pacote 'br.com.ead' como TRACE, que é o nível mais detalhado.
    root: info  # Define o nível de logging padrão (root) como INFO, que é um nível de logging intermediário.
    org.springframework.web: debug  # Define o nível de logging para o pacote 'org.springframework.web' como DEBUG, útil para depurar problemas relacionados ao Spring Web.
    org.hibernate: debug
